# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=b'example/media/images'),
        ),
    ]
